### PR TITLE
Add option for package maintainer scripts 

### PR DESCRIPTION
**Pull request by fcastilloec**

### CODE REVIEW

**Comment by fcastilloec** [comment]
@unindented is there a chance you can review this PR? I really would like to have this feature for my next project

**Comment by unindented** [comment]
Sure, PR looks good. Can you add tests so that I can merge it in?

**Comment by fcastilloec** [comment]
I'm very new to javascript and nodejs so I'll try to figure out how to do it, but it might take a while. I just started a couple of weeks ago, so maybe you can point me in the right direction to speed things up.

**Comment by unindented** [comment]
The existing tests should help you get started.

**Comment by fcastilloec** [comment]
It seems that it wasn't as hard as I thought it was. I didn't create a new test just added it to the `with an app without asar`, since that is testing all configuration options. Let me know what you think

**Comment by fcastilloec** [comment]
I also wanted to point out that the test will fail if the scripts aren't executable or have weird permission, `dpkg-deb --build` checks for permission and throws an error acordingly, so we don't have to.

**Comment by fcastilloec** [comment]
@unindented I've worked on your code a little more and have added some changes to fix a lot of the lintian warnings and errors, mainly the file and directory permissions. Those changes are not really related to what this PR is doing.
If you think that this PR is ok (or if any changes, let me know), you could merge it and submit a new one addressing the lintian errors and warnings, including a test for it.

**Comment by unindented** [comment]
This looks good to me. You've tested it with your use case and everything's running fine?

**Comment by unindented** [comment]
I assume you have. Please open a PR for the new stuff. Thank you!

**Comment by fcastilloec** [comment]
Thanks! I'll be submitting the new PR soon, it has a lot more changes so I really would like your opinion.

**Comment by fcastilloec** [comment]
I also notice that Travis is failing because `fakeroot`, `dpkg` and `lintian` are not installed by default and have to be added to the dependencies. That will be addressed on the new PR.

**Pull request merged**
