### PR TITLE
Remove unnecessary packages from the default dependency list

### LINKED ISSUE #52: Dependencies
Hello. 

Why `git` and `python` were put in the list of package dependencies?

### PR DESCRIPTION
**Pull request by malept**
Also alphabetizes the dependency list.

Fixes #52.

### CODE REVIEW

**Comment by unindented** [comment]
👍 

Have you tried packaging one of your apps, and checking that everything still works? I'm moving countries right now, and don't have much free time...

**Comment by malept** [comment]
Works for me. Tested with `electron-forge init && electron-forge make && sudo gdebi out/make/*_amd64.deb` with an Electron Forge instance that uses this PR. Admittedly, I already have git and python installed, so it's kind of a weird test. A "real" test would involve a clean Linux VM with a minimal X11 install.

**Comment by unindented** [comment]
Let's merge it then.

**Comment by malept** [comment]
@unindented I know you're busy right now, but do you have some time soon to release a new version with this? That would probably cut down on the number of issues like #54 that are filed.

**Comment by unindented** [comment]
`v0.5.0` contains your fix.

**Comment by malept** [comment]
Thanks!

**Pull request merged**
