### PR TITLE
Release 1.0.0

### LINKED ISSUE #136: Release 1.0.0
This issue should describe the criteria for releasing 1.0.0.

* [x] #120 
* [x] Drop callback support (#138)
* [ ] Drop Node 4 support (#145)

### PR DESCRIPTION
**Pull request by malept**
:tada: :tada:

Fixes #136.

### CODE REVIEW

**Comment by malept** [comment]
Well, I tried to publish and it didn't work: https://travis-ci.org/unindented/electron-installer-debian/jobs/437873831#L2273-L2289

@unindented I think the NPM API key in Travis needs to be updated. Once that's fixed, we can delete the 1.0.0 tag and try again.

**Comment by fcastilloec** [comment]
Yes, @unindented needs to updated the API key. I forgot that `npm` invalidated all tokens issued before 2018-07-12 due to a security breach. https://status.npmjs.org/incidents/dn7c1fgrr7ng

**Comment by unindented** [comment]
Sorry folks, I was busy moving apartments... I'll update now.

Also @malept, @fcastilloec can you confirm your npmjs.org aliases? I'll add you as collaborators there.

**Comment by unindented** [comment]
@malept @fcastilloec I've manually published `1.0.0` in the meantime, and opened a PR to update the npm key: https://github.com/unindented/electron-installer-debian/pull/147

I'll be doing the same for `electron-installer-redhat`.

**Comment by fcastilloec** [comment]
@unindented Thanks for pushing the new version manually. My `npmjs.org` username is `fcastilloec`

**Comment by malept** [comment]
> can you confirm your npmjs.org aliases?

I'm `malept` there as well.

> Also, would you be ok with moving this under the `electron-userland` org? Who would we contact?

I'm OK with this, but I may be biased as I'm one of the `electron-userland` admins :smile:

**Comment by unindented** [comment]
@malept haha awesome. Could you drive the move of both `electron-installer-debian` and `electron-installer-redhat`? Feel free to change all copyright notices, URLs, and whatever you need to be compatible with the new org.

(I don't know if anybody is interested in `electron-installer-windows` because of the overlap with `electron-winstaller`, but I'm cool with moving that one too.)

**Comment by malept** [comment]
@unindented the only thing you're required to do is accept the electron-userland org invite, and transfer ownership of the repos to the org.

**Comment by unindented** [comment]
LET'S DO IT

**Comment by fcastilloec** [comment]
I'm not an admin at `electron-userland` so if we move, I'm not sure if they will add me as an admin there. Nonetheless, I'll keep contributing.

**Comment by unindented** [comment]
@malept done for all three repos. Can you make sure @fcastilloec keeps necessary access to them?

Thank you both for keeping these projects alive! 🙌

**Comment by malept** [comment]
@fcastilloec you'll still be a contributor to the three repos, it's not necessary to be an admin/member of the org.

**Comment by malept** [comment]
I will work on updating the URLs and such some time this week (my month just got very busy) unless @fcastilloec beats me to it.

I also need to add the packages to the `electron-userland` NPM org.

**Comment by unindented** [comment]
Thank you!

**Pull request merged**
