### PR TITLE
Support custom desktop file templates

### PR DESCRIPTION
**Pull request by malept**
This should also support the use case where the desktop file is pre-generated.

Also fixes a typo in a comment.

### CODE REVIEW

**Comment by fcastilloec** [comment]
You're going to need to add `fakeroot` and `dpkg` to Travis for the build to pass

**Comment by malept** [comment]
I *just* noticed the `fakeroot` problem, I'll add `dpkg` too.

Should I just file a PR to do that?

**Comment by fcastilloec** [comment]
@malept previous Travis versions needed both it seems that now only `fakeroot` is needed. The build is passing so all is good

**Comment by malept** [comment]
This PR now requires #99 to be merged.

**Comment by fcastilloec** [comment]
Great PR, this will allow people to put/remove any desktop key they want, without `electron-installer-debian` having to support it. I opened issue #84 for Keywords key which this PR will address.
This PR can also be merged with my PR without any changes. We just have to wait for @unindented to approve of both of our PRs

**Comment by unindented** [comment]
@malept @fcastilloec would you be interested in becoming contributors, so that you're not blocked by me?

**Comment by malept** [comment]
I don't mind.

**Comment by fcastilloec** [comment]
I don't mind either. This way PR can get approved by more people before merging them

**Comment by unindented** [comment]
You're contributors now. If you want to release a new version at any point, just create a new branch, `npm version patch -m "Release version %s"` or whatever, and open a PR. When merged, it will automatically publish the new version to npm.

**Comment by fcastilloec** [comment]
Great! Thanks

**Pull request merged**
